name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, bcmath, gmp

      - name: Initial application
        run: |
          cp .env.example .env
          composer install -o --no-interaction --no-progress
          php artisan key:generate
          php artisan storage:link
          yarn
          yarn run production

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Checkout latest docs
        run: |
          git config --global url.https://github.com/.insteadOf git@github.com:
          source bin/checkout_latest_docs.sh

      - name: Build API documentation
        run: base=`pwd` build/api.sh

      - name: Cache website
        run: php artisan cache-site
